version: '3'

x-node:
  &default-node
  build: ./node
  privileged: true
  networks:
    - gorgon-net
  ports:
    - 9080
  deploy:
    resources:
      limits:
        cpus: 2
        memory: 3G
  mem_swappiness: 1

x-control:
  &control-node
  build: ./control
  privileged: true
  networks:
    - gorgon-net
  deploy:
    resources:
      limits:
        cpus: 2
        memory: 4G
  mem_swappiness: 1

services:
  control:
    << : *control-node
    container_name: gorgon-control
    hostname: control
  n0:
    << : *default-node
    container_name: gorgon-n0
    hostname: n0
  n1:
    << : *default-node
    container_name: gorgon-n1
    hostname: n1
  n2:
    << : *default-node
    container_name: gorgon-n2
    hostname: n2
  n3:
    << : *default-node
    container_name: gorgon-n3
    hostname: n3
  n4:
    << : *default-node
    container_name: gorgon-n4
    hostname: n4

networks:
  - gorgon-net
