networks:
  gorgon-net: {}

services:
  control:
    container_name: gorgon-control
    hostname: control.local
    image: gorgon_couchbase-control
    build: ./control
    pull_policy: never
    privileged: true
    networks:
      - gorgon-net
    environment:
      NODES: "n0.local,n1.local,n2.local"
    cpu_count: 4
    mem_limit: 4G
    mem_swappiness: 1
  n0:
    container_name: gorgon-n0
    hostname: n0.local
    image: gorgon_couchbase-node
    pull_policy: never
    privileged: true
    networks:
      - gorgon-net
    ports:
      - "8090:8091"
    cpu_count: 2
    mem_limit: 3G
    mem_swappiness: 1
    build: ./node
  n1:
    container_name: gorgon-n1
    hostname: n1.local
    image: gorgon_couchbase-node
    pull_policy: never
    privileged: true
    networks:
      - gorgon-net
    ports:
      - "8091:8091"
    cpu_count: 2
    mem_limit: 3G
    mem_swappiness: 1
  n2:
    container_name: gorgon-n2
    hostname: n2.local
    image: gorgon_couchbase-node
    pull_policy: never
    privileged: true
    networks:
      - gorgon-net
    ports:
      - "8092:8091"
    cpu_count: 2
    mem_limit: 3G
    mem_swappiness: 1
