x-node:
  &default-node
  pull_policy: never
  privileged: true
  networks:
    - gorgon-net
  cpu_count: 2
  mem_limit: 3G
  mem_swappiness: 1

services:
  control:
    container_name: gorgon-control
    hostname: control.local
    image: gorgon_couchbase-control
    build: ./control
    pull_policy: never
    privileged: true
    networks:
      - gorgon-net
    cpu_count: 4
    mem_limit: 3G
    mem_swappiness: 1
  n0:
    << : *default-node
    container_name: gorgon-n0
    hostname: n0.local
    image: gorgon_couchbase-node
    build: ./node
    ports:
      - "8090:8091"
  n1:
    << : *default-node
    container_name: gorgon-n1
    hostname: n1.local
    image: gorgon_couchbase-node
    ports:
      - "8091:8091"
  n2:
    << : *default-node
    container_name: gorgon-n2
    hostname: n2.local
    image: gorgon_couchbase-node
    ports:
      - "8092:8091"

networks:
  gorgon-net: {}
